service.config:
  service: your-service
  serviceInstance: your-service-instance
server.monitor:
  collectInterval: 1
  consumeInterval: 60
  timeunit: SECONDS
druid.monitor:
  collectInterval: 1
  consumeInterval: 10
  timeunit: SECONDS